version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  pgdata:
  redisdata:
